
server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/kotlinblog?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8mb4
    username: test
    password: Test@12345678
#    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true



